Switch to Jazzy and drop Iron support
CWRUbotix/rov-25 pull request #51
Opened 2024-07-12 12:46 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Drops Iron support.

## Related Tickets & Documents

- Related Issue #
#11 
- Closes #
#11

2024-08-01 13:18 UTC, benjaminwp18 requested changes

2024-08-01 13:18 UTC, benjaminwp18 commented on src/surface/rov_flir/README.md
> +Run the setup file from spinnaker_camera_driver cannot be in VSCode for some reason.
```suggestion
Run the following spinnaker_camera_driver setup from a regular terminal. Don't run it in the VSCode terminal (it doesn't work there for some reason).
```

2024-08-01 13:18 UTC, benjaminwp18 commented on src/surface/rov_flir/launch/flir_launch.py
> +        # 'image_height': 1080,
Group together and add a comment explaining the lines that control whether jumbo packets are enabled

2024-08-01 13:20 UTC, InvincibleRMC commented on src/surface/rov_flir/launch/flir_launch.py
>          # These are useful for GigE cameras
```suggestion
        # These are useful for GigE cameras (Jumbo packets)
```

2024-08-03 19:55 UTC, benjaminwp18 approved these changes

2024-08-03 19:55 UTC, merged