update dep
CWRUbotix/rov-25 pull request #9
Opened 2024-07-03 18:43 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

2024-07-03 20:52 UTC, InvincibleRMC commented
After this just need spinnaker and jazzy should be gtg.

2024-07-06 19:16 UTC, benjaminwp18 requested changes

2024-07-06 19:16 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/video_widget.py
> +# MatLike = NDArray[numpy.integer[Any] | numpy.floating[Any]]/
Explain why this is here and label each of these alternatives

2024-07-06 19:21 UTC, benjaminwp18 requested changes

2024-07-06 19:21 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/video_widget.py
> +# This should be posiible in a newer version of mypy, MatLike = NDArray[numpy.integer[Any] | numpy.floating[Any]]
```suggestion
# This what is actually implemented in cv2.typing:
# MatLike = cv2.mat_wrapper.Mat | NDArray[numpy.integer[Any] | numpy.floating[Any]]
# This should be possible in a newer version of mypy:
# MatLike = NDArray[numpy.integer[Any] | numpy.floating[Any]]
```

2024-07-06 19:22 UTC, benjaminwp18 approved these changes

2024-07-06 19:22 UTC, merged