Change button colors on arm and disarm
CWRUbotix/rov-25 pull request #99
Opened 2024-10-05 19:49 UTC by ShannonGriswold

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Change the colors of the arm and disarm buttons depending on whether the robot is armed or disarmed
## Related Tickets & Documents

- Related Issue #
- Closes #94

2024-10-05 20:36 UTC, benjaminwp18 requested changes
This works great in simulation 🎉

But... I don't like how it only applies to the `Arm` widget. The `Arm` widget uses two `ButtonIndicator`s for its buttons, which inherit from our custom `IndicatorMixin` widget class. `IndicatorMixin` is also inherited by `CircleIndicator`, which made pretty green/red circles for statuses like flooding & Pi connection.

`CircleIndicator` used broken code that switched between stylesheets that are defined in `surface/gui/gui/styles` (the `.qss` files). I kinda like your solution (defining the stylesheets in code and switching between them just by setting the stylesheet) better, but I want your solution to work for everything that inherits from `IndicatorMixin`. Can you update this to work from `IndicatorMixin`?

2024-11-02 18:13 UTC, benjaminwp18 requested changes

2024-11-02 18:13 UTC, benjaminwp18 commented on src/surface/gui/gui/styles/custom_styles.py
> +        self._ORIGINAL_STYLESHEET = self.styleSheet()
SCREAMING_SNAKE is for constants, make this `self._original_stylesheet`

2024-11-09 19:23 UTC, benjaminwp18 requested changes

2024-11-09 19:23 UTC, benjaminwp18 commented on src/surface/gui/gui/styles/custom_styles.py
> +        return ''
Store `_ON_STYLESHEET` etc. in a dictionary of `WidgetState`s -> stylesheets

2024-11-12 23:33 UTC, InvincibleRMC commented on src/surface/gui/gui/styles/custom_styles.py
> +class WidgetState(Enum):
use IntEnum

2024-11-16 18:44 UTC, benjaminwp18 approved these changes
🥳

2024-11-16 19:02 UTC, merged